### ISSUE TITLE
Use newer SSE2NEON

### ISSUE THREAD

**Issue by jserv** [lighttransport/embree-aarch64#25]
Current [common/math/SSE2NEON.h](https://github.com/lighttransport/embree-aarch64/blob/master/common/math/SSE2NEON.h) was derived from older SSE2NEON. Meanwhile, [DLTcollab/sse2neon](https://github.com/DLTcollab/sse2neon) is actively maintained and collaborate with more developers.

I would like to propose the changes to take [DLTcollab/sse2neon](https://github.com/DLTcollab/sse2neon)  and work on the pending issues like #24 .

**Comment by syoyo** [comment]
@jserv Super awesome! Yes, PR of updating SSE2NEON with https://github.com/DLTcollab/sse2neon  is appreciated!
