### ISSUE TITLE
SSE2NEON mapping for _mm_sqrt_ps(0) does not return 0

### ISSUE THREAD

**Issue by maikschulze** [lighttransport/embree-aarch64#30]
The NEON-mapped function _mm_sqrt_ps does not handle zero inputs properly. Instead of returning 0, it returns a NaN value. This is caused by the underyling function 'vrsqrteq_f32' which returns +inf. 

This affects CylinderN::intersect such that
`const vfloat<N> Q = sqrt(D);`
would not work properly if D=0, resulting in a false miss.

This can be reproduced on arm64 (not on x64) with the following ray in the interpolation scene:

```
  {
    RTCIntersectContext context;
    rtcInitIntersectContext(&context);

    RTCRayHit rayhitdebug;
    rayhitdebug.ray.org_x = -0.000000476837158;
    rayhitdebug.ray.org_y = 4.99999952;
    rayhitdebug.ray.org_z = -7.07106781;

    rayhitdebug.ray.dir_x = 0.645600736;
    rayhitdebug.ray.dir_y = -0.512669444;
    rayhitdebug.ray.dir_z = 0.566012084;

    rayhitdebug.ray.time = 0.0;
    rayhitdebug.ray.tnear = 0.0;
    rayhitdebug.ray.tfar = 100000.0;
    rayhitdebug.ray.mask = -1;
    rayhitdebug.ray.id = 0;
    rayhitdebug.ray.flags = 0;

    Vec3fa xx(-1, 0, 1);
    Vec3fa yy = rsqrt(xx);
    Vec3fa zz = sqrt(xx);

    rtcIntersect1(g_scene, &context, &rayhitdebug);
  }
```

**Comment by syoyo** [comment]
At least the issue has been fixed by merging #31 

As a TODO, we are better to implement precice sqrt implementation(get same result with SSE2 sqrt) in NEON

Fortunately NEON itself provides sqrt instruction(`vsqrtq_f32`) so we can start with it:

```
#include <cstdint>
#include <cstdio>
#include <cmath>
#include <limits>

#include <arm_neon.h>

struct FP32
{
  union {
    float f;
    uint32_t ui;
  };
};

void print_value(float x)
{
  float32x4_t a = vdupq_n_f32(x);

  float32x4_t c = vsqrtq_f32(a);

  __attribute__((aligned(16))) float buf[4];

  vst1q_f32(buf, c);

  FP32 fp;
  fp.f = buf[0];

  printf("sqrt(%g) = %g(0x%08x)\n", x, buf[0], fp.ui);

};

int main(int argc, char **argv)
{
  print_value(0.0f);
  print_value(-0.0f);
  print_value(std::numeric_limits<float>::infinity());
  print_value(-std::numeric_limits<float>::infinity());
  print_value(-1.0f);

  return 0;
}
```
```
sqrt(0) = 0(0x00000000)
sqrt(-0) = -0(0x80000000)
sqrt(inf) = inf(0x7f800000)
sqrt(-inf) = nan(0x7fc00000)
sqrt(-1) = nan(0x7fc00000)
```


Here is `_mm_sqrt_ps` version

```
#include <cstdint>
#include <cstdio>
#include <cmath>
#include <limits>

#include <xmmintrin.h>

struct FP32
{
  union {
    float f;
    uint32_t ui;
  };
};

void print_value(float x)
{
  __m128 a = _mm_set1_ps(x);

  __m128 c = _mm_sqrt_ps(a);

  float buf[4];

  _mm_storeu_ps(buf, c);

  FP32 fp;
  fp.f = buf[0];

  printf("sqrt(%g) = %g(0x%08x)\n", x, buf[0], fp.ui);

};

int main(int argc, char **argv)
{
  print_value(0.0f);
  print_value(-0.0f);
  print_value(std::numeric_limits<float>::infinity());
  print_value(-std::numeric_limits<float>::infinity());
  print_value(-1.0f);

  return 0;
}
```

```
sqrt(0) = 0(0x00000000)
sqrt(-0) = -0(0x80000000)
sqrt(inf) = inf(0x7f800000)
sqrt(-inf) = -nan(0xffc00000)
sqrt(-1) = -nan(0xffc00000)
```

SSE sqrt preserves(?) sign bit for nan case.

## sqrt in cmath

https://en.cppreference.com/w/cpp/numeric/math/sqrt

At least SSE2 and NEON's sqrt instruction follows the behavior of cmath(IEEE754?) `sqrt` .

## Conclusion

If we use `vsqrtq_f32`, it should give (mostly) identical result with SSE2 `_mm_sqrt_ps`(only the difference is the sign bit of NaN case).

If we use reciprocal estimate implementation, we'll need to care about `+-0.0`, `+-inf` and negative values.

**Comment by maikschulze** [comment]
Hi @syoyo , thank you very much for merging my code change. I agree, we might be better off replacing the entire mechanism with vsqrtq_f32. I don't see how we can get away without refinement iterations and the added complexity to handle the special values might not make the current approach worthwhile.

**Comment by syoyo** [comment]
Close the issue since the fix has been merged https://github.com/lighttransport/embree-aarch64/pull/31

@maikschulze Thanks for the investigation and PR!
