### ISSUE TITLE
Code Changes that impact x64

### ISSUE THREAD

**Issue by maikschulze** [lighttransport/embree-aarch64#36]
Hi,

I would like to report findings of a code we have performed to assess the impact of this 'fork' onto x64. Please understand that my listing below should not be treated as a list of defects, but rather present the differences to the original code base. I would like raise awareness of these changes and have a discussion about them.

We did execute one elaborate performance test of the 3.11 state which amounted to a low single-digit performance drop in comparison to the original code.

The following changes were identified. The screenshots show the Intel code (left) in comparison with the master branch of this repository (right).

### 1. sign in vec3fa.h

![image](https://user-images.githubusercontent.com/4232812/94796596-48dd8700-03df-11eb-90c8-810a64806839.png)

### 2. comparison intrinsics in vec3fa.h and vfloat_sse2.h

![image](https://user-images.githubusercontent.com/4232812/94796842-9eb22f00-03df-11eb-89d4-936260ebf6a7.png)

![image](https://user-images.githubusercontent.com/4232812/94796900-b12c6880-03df-11eb-9e9f-4f23caf818f7.png)

### 3. Change of mask computation in intersectNode in node_intersector1.h

![image](https://user-images.githubusercontent.com/4232812/94797364-4e879c80-03e0-11eb-9592-123d56bc51e8.png)

### 4. Replacement of vreduce_min/max with reduce_min/max in vfloat8_avx.h

![image](https://user-images.githubusercontent.com/4232812/94798088-64e22800-03e1-11eb-8c9d-0596754c73fd.png)

This code change is introduced with pull request https://github.com/lighttransport/embree-aarch64/pull/34 .

### 5. Change to rcp_safe in vec3fa.h

![image](https://user-images.githubusercontent.com/4232812/94798306-bf7b8400-03e1-11eb-8283-0efe1dbf39be.png)

Has the been a strong reason for any of these code changes, do we have confidence they are all acceptable? Please let me know whether you regard any of these code changes risky or avoidable. I will gladly prepare a pull request. Personally, I would favor to revert or ifdef these points to be on the safe side.

**Comment by syoyo** [comment]
@maikschulze Nice report! We'd be better to use original Intel embree code(upstream)  as much as possible, so PR is appreciated.

I think we had missed keeping up with upstream codebase for some reason when merging.

**Comment by maikschulze** [comment]
Thank you for the quick response, @syoyo . I will prepare a pull request tomorrow that ensures original behavior on x64 in these code areas.

**Comment by syoyo** [comment]
PR has been merged so close the issue
