### ISSUE TITLE
verify NEON.update failure in recent commit(at least from v3.11.0) 

### ISSUE THREAD

**Issue by syoyo** [lighttransport/embree-aarch64#38]
`NEON.update` in verity started to fail at some point(but could be reproducible from v3.11.0)

OS: aarch64 linux(Jetson AGX)
Build config: `./scripts/build-aarch64-linux.sh`

```
Embree Ray Tracing Kernels 3.11.0 (4a0f1750c6848437bf0d2f83c10863990caadda1)
  Compiler  : GCC 7.5.0
  Build     : Release 
  Platform  : Linux (32bit)
  CPU       : Unknown CPU ( MRA MRA MRA)
   Threads  : 8
   ISA      : SSE SSE2 NEON 
   Targets  : 
   MXCSR    : FTZ=0, DAZ=0
  Config
    Threads : default
    ISA     : SSE SSE2 NEON 
    Targets :  (supported)
              SSE2  (compile time enabled)
    Features: intersection_filter 
    Tasking : internal_tasking_system 

================================================================================
  WARNING: "Flush to Zero" or "Denormals are Zero" mode not enabled 
           in the MXCSR control and status register. This can have a severe 
           performance impact. Please enable these modes for each application 
           thread the following way:

           #include "xmmintrin.h"
           #include "pmmintrin.h"

           _MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON);
           _MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON);
================================================================================


 [PASSED]
                                                       fast_allocator_regression_test ... [PASSED]
                                                         motion_derivative_regression ... [PASSED]
                                                            collision_regression_test ... [PASSED]
                                                                cache_regression_test ... [PASSED]
                                                         parallel_for_regression_test ... [PASSED]
                                                      parallel_reduce_regression_test ... [PASSED]
                                                       parallel_prefix_sum_regression ... [PASSED]
                                                     parallel_for_for_regression_test ... [PASSED]
                                          parallel_for_for_prefix_sum_regression_test ... [PASSED]
                                                   parallel_partition_regression_test ... [PASSED]
                                                           RadixSortRegressionTestU32 ... [PASSED]
                                                           RadixSortRegressionTestU64 ... [PASSED]
                                                         parallel_set_regression_test ... [PASSED]
                                                         parallel_map_regression_test ... [PASSED]
                                                           parallel_filter_regression ... [PASSED]
                                                          barrier_sys_regression_test ... [PASSED]
                                                                NEON.multiple_devices ... [PASSED]
                                                                      NEON.types_test ... [PASSED]
                                                                      NEON.get_bounds ...++++++ [PASSED]
                                                               NEON.get_linear_bounds ...++++++ [PASSED]
                                                                   NEON.get_user_data ... [PASSED]
                                                                   NEON.buffer_stride ...++++++++ [PASSED]
                                                                     NEON.empty_scene ...++++++++++ [PASSED]
                                                                  NEON.empty_geometry ...++++++++++ [PASSED]
                                                                           NEON.build ...++++++++++ [PASSED]
                                                          NEON.overlapping_primitives ...++++++++++ [PASSED]
                                                             NEON.new_delete_geometry ................................................................................................................................+++++ [PASSED]
                                                                NEON.user_geometry_id ...+++++ [PASSED]
                                                         NEON.enable_disable_geometry ...+++++ [PASSED]
                                                                          NEON.update ...-----+++++-++-+++++-++-+++--+-+-+---+-++-+-+--+++-+-+---++++---+-+-+-++---+-+-++-+--+-++++++++++++++++++++++++++-++-++++++++++++++++++++++++++-++--++++-+++++++++++-+++-++++++++++++++++++++++++++-++-++-+-++++++++++++++-+++---+++++++++++++---++++--+-+-+-++++++++++++++-+--++-++++++++++++++++++++++++++++++++++++++-+--+++--+++----+----+-+---+---++--++--+-+++++++++++++++++++++++++++++++++++++++++++++++-+---+++++-+++-+---+++--++++---+-+---+--+-+-+++-++++++++++++++++++++++++-+++++-+-++++++++++++++++++++++++++++++++++++++++ [FAILED]
                                                              NEON.build_garbage_geom ..................................................... [PASSED]
...
```

**Comment by syoyo** [comment]
The issue only happens when `EMBREE_RAY_PACKETS=On`

**Comment by maikschulze** [comment]
I can confirm that NEON.update used to work and now fails.

For no particular reason, I've selected to track the introduction of FAILED for
std::vector<std::string> arguments = { "", "--no-colors", "--run .*SSE2.update.dynamic.DynamicFast.LowQuality.Intersect4.*", "--sequential" };
, which is 1 of 120 update tests now failing.

I can confirm that:
https://github.com/lighttransport/embree-aarch64/commit/8246a54c10774aeeaa69486811d02a09cdb87365 PASSED
https://github.com/lighttransport/embree-aarch64/commit/4ecf7063678769f0145926c890815acc3825a3cf PASSED
https://github.com/lighttransport/embree-aarch64/commit/ba6d997e66d8d15dc176727857900637be0bc832 FAILED

I briefly debugged into the failure but could not pinpoint the cause. There are minute numerical differences that eventually lead to different branching, but nothing particular stands point.

Any idea what might cause it?

**Comment by maikschulze** [comment]
I was able to pin-point the failure to a single line of code that was introduced with https://github.com/lighttransport/embree-aarch64/commit/5f3350facc6a1dae64c732221d8c3a6d77f51065

I ran the 'verify' suite before and after with packets enabled:
![image](https://user-images.githubusercontent.com/4232812/95777133-e54c3700-0cc5-11eb-82d9-4240e0b8fb81.png)

[verify_before_sse2_with_packets.txt](https://github.com/lighttransport/embree-aarch64/files/5366812/verify_before_sse2_with_packets.txt)
[verify_before_avx2_with_packets.crashlog.txt](https://github.com/lighttransport/embree-aarch64/files/5366811/verify_before_avx2_with_packets.crashlog.txt)

[verify_after_sse2__with_packets.txt](https://github.com/lighttransport/embree-aarch64/files/5366810/verify_after_sse2__with_packets.txt)
[verify_after_avx2__with_packets.crashlog.txt](https://github.com/lighttransport/embree-aarch64/files/5366809/verify_after_avx2__with_packets.crashlog.txt)

For SSE2 / NEON, all tests will pass.

Since the reversal will impact performance to a significant degree, I refrain from making such a merge request right away. I suggest to investigate the numerical behavior over the next days. Maybe we come up with a better solution.

I believe the "AVX2 emulation"-related crashes are caused by access to functions that are not present because of the absence of the "AVX" code path. We may have to improve the function dispatch for NEON2X in this regard. I will debug into this more closely.

**Comment by Developer-Ecosystem-Engineering** [comment]
Patch incoming

**Comment by syoyo** [comment]
PR #44 has been merged and `update` test in `verify` all passes for every ISA configuration(NEON, AVX). So I think its ready to close this issue.

**Comment by maikschulze** [comment]
I agree, I also think this issue has been fixed. Many thanks to @Developer-Ecosystem-Engineering !

**Comment by syoyo** [comment]
@maikschulze @Developer-Ecosystem-Engineering :tada:

I have updated README: https://github.com/lighttransport/embree-aarch64/commit/54a6ebc2e97f5a9980d674c42dbd7fda0a212ba2
