### ISSUE TITLE
create releases

### ISSUE THREAD

**Issue by tsahee** [lighttransport/embree-aarch64#47]
This embree-fork is very useful. I was able to use it with blender on arm64 with very little effort.

To be able to use it in other software and installation scripts, it would be helpful if embree-aarch64 will have official releases, which could be downloaded as tar.gz according to version number.

Thank you!

**Comment by syoyo** [comment]
We recommend to use embree-aarch64 as a git submodule.

> it would be helpful if embree-aarch64 will have official releases, which could be downloaded as tar.gz according to version number

github supports creating a release by simply tagging the git repo so I made an experimental one: `v3.12.1-aarch64`: https://github.com/lighttransport/embree-aarch64/releases

To avoid tag name conflict when merging/syncing with Intel Embree git repo, I have added `-aarch64` suffix to the tag name.

Is this the expected one?

**Comment by tsahee** [comment]
The directory name becomes a little weird: "embree-aarch64-3.12.1-aarch64", but I understand where it's coming from. I can work with that.

Thank you!

**Comment by syoyo** [comment]
yes, its weird but it'd be acceptable. FYI we use `aarch64-vX.Y.Z` as a branch name for each corresponding release.

**Comment by syoyo** [comment]
@tsahee I think this issue is ready to close.

**Comment by tsahee** [comment]
Thank you!
