### ISSUE TITLE
TODO: Test grid geometry

### ISSUE THREAD

**Issue by syoyo** [lighttransport/embree-aarch64#8]

**Comment by maikschulze** [comment]
I can report that grid geometry renders fine on ARM64.

I validated this by porting the Embree tutorial for grid geometry to an Android app and obtain this result:

![GridGeometry_010](https://user-images.githubusercontent.com/4232812/59247108-99473900-8c1e-11e9-85fa-28f8d2a642b6.png)

I did experience numerical precision issues with displacement, grid, point and curve geometries. They all seem to relate to problems with rcp and rsqrt and its lack of precision. Performing two Newton-Raphson iterations does seem to address all these issues:
https://github.com/maikschulze/embree-aarch64/commit/e17f69627ee2157f20c550eeb4f7d76c3c86ac36

**Comment by syoyo** [comment]
Thank you!

>  Performing two Newton-Raphson iterations does seem to address all these issues:
maikschulze@e17f696

Since your changes has been merged with this PR,

https://github.com/lighttransport/embree-aarch64/pull/10

I think its ready to close this issue.

**Comment by syoyo** [comment]
Close this issue thanks to this PR : https://github.com/lighttransport/embree-aarch64/pull/11
